import type { Metadata } from 'next'
import './css/globals.css'
import './css/style.css'

export const metadata: Metadata = {
  title: 'Jestin | Frontend Web Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
